name: PTBEnv
channels:
  - defaults
  - conda-forge
dependencies: 
  - python=3.11
  - pip
  - numpy=1.24
  - cython
  - scipy
  - h5py
  - pyfftw
  - nibabel
  - lmfit
  - numdifftools
  - dominate
  - imageio
  - matplotlib
  - psutil
  - pandas
  - scikit-image
  - scikit-learn
  - hdf5storage
  - pydicom
  - tqdm
  - more-itertools
  - pynufft
  - pip:
    - pylbfgs
    - ksvd
    - git+https://github.com/stefanloock/pyshearlab/@master

  
    
