name: PTBEnv
channels:
  - defaults
  - conda-forge
dependencies: 
  - python=3.8
  - pip
  - numpy
  - cython
  - scipy
  - h5py
  - pyfftw
  - nibabel
  - lmfit
  - numdifftools
  - dominate
  - imageio
  - matplotlib
  - psutil
  - pandas
  - scikit-image
  - hdf5storage
  - pydicom
  - tqdm
  - pip:
    - pylbfgs
    - ksvd
    - pynufft
    - sklearn
    - more_itertools
    - git+https://github.com/stefanloock/pyshearlab/@master

  
    
